# Generated by Django 4.2.5 on 2023-09-25 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_movimentacao', models.DecimalField(decimal_places=0, max_digits=4)),
                ('mes_movimentacao', models.DecimalField(decimal_places=0, max_digits=2)),
                ('orgao_codigo', models.DecimalField(decimal_places=0, max_digits=10)),
                ('orgao_nome', models.TextField()),
                ('unidade_codigo', models.DecimalField(decimal_places=0, max_digits=10)),
                ('unidade_nome', models.TextField()),
                ('categoria_economica_codigo', models.DecimalField(decimal_places=0, max_digits=10)),
                ('categoria_economica_nome', models.TextField()),
                ('grupo_despesa_codigo', models.DecimalField(decimal_places=0, max_digits=10)),
                ('grupo_despesa_nome', models.TextField()),
                ('modalidade_aplicacao_codigo', models.DecimalField(decimal_places=0, max_digits=10)),
                ('modalidade_aplicacao_nome', models.TextField()),
                ('elemento_codigo', models.DecimalField(decimal_places=0, max_digits=10)),
                ('elemento_nome', models.TextField()),
                ('subelemento_codigo', models.DecimalField(decimal_places=0, max_digits=10)),
                ('subelemento_nome', models.TextField()),
                ('funcao_codigo', models.DecimalField(decimal_places=0, max_digits=10)),
                ('funcao_nome', models.TextField()),
                ('subfuncao_codigo', models.DecimalField(decimal_places=0, max_digits=10)),
                ('subfuncao_nome', models.TextField()),
                ('programa_codigo', models.DecimalField(decimal_places=0, max_digits=10)),
                ('programa_nome', models.TextField()),
                ('acao_codigo', models.DecimalField(decimal_places=0, max_digits=10)),
                ('acao_nome', models.TextField()),
                ('fonte_recurso_codigo', models.DecimalField(decimal_places=0, max_digits=10)),
                ('fonte_recurso_nome', models.TextField()),
                ('empenho_ano', models.DecimalField(decimal_places=0, max_digits=4)),
                ('empenho_modalidade_nome', models.TextField()),
                ('empenho_modalidade_codigo', models.DecimalField(decimal_places=0, max_digits=10)),
                ('empenho_numero', models.DecimalField(decimal_places=0, max_digits=10)),
                ('subempenho', models.DecimalField(decimal_places=2, max_digits=15)),
                ('indicador_subempenho', models.TextField()),
                ('credor_codigo', models.DecimalField(decimal_places=0, max_digits=10)),
                ('credor_nome', models.TextField()),
                ('modalidade_licitacao_codigo', models.DecimalField(decimal_places=0, max_digits=10)),
                ('modalidade_licitacao_nome', models.TextField()),
                ('valor_empenhado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valor_liquidado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
            },
        ),
    ]
